baseURL: 'http://status.bain.cz/'
languageCode: 'en-us'
title: 'bain.cz status'
buildFuture: true

params:
  services:
    - f.bain.cz
    - s.bain.cz
    - ts3.bain.cz
    - git.bain.cz

taxonomies:
  affected: affected

