baseURL: 'https://status.bain.cz/'
languageCode: 'en-us'
title: 'bain.cz status'
buildFuture: true

params:
  services:
    - f.bain.cz
    - s.bain.cz
    - git.bain.cz
    - vault.bain.cz

taxonomies:
  affected: affected

