name: Build
on:
  push:
    branches: [ master ]
    paths: [ src/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo
      
      - name: Build website
        run: |
          mkdir -p build
          cd src
          hugo -d ../build
      
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: status.bain.cz
